services:
  nocodb:
    image: "nocodb/nocodb:latest"
    container_name: nocodb
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      nocodb_data:
        condition: service_healthy
    environment:
      NC_DB: "pg://nocodb_data:5432?u=postgres&p=password&d=nocodb_admin"
    volumes:
      - "nc_data:/usr/app/data"
  nocodb_data:
    image: postgres
    container_name: nocodata
    environment:
      POSTGRES_DB: nocodb_admin
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: postgres
    ports:
      - "5555:5432"
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    restart: always
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:
    driver: local
  nc_data:
    driver: local
